"""Add location to project

Revision ID: 107cea9ee024
Revises: 4ac45320f20c
Create Date: 2023-02-19 00:20:48.487242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107cea9ee024'
down_revision = '4ac45320f20c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projet', 'location')
    # ### end Alembic commands ###
