"""table projet slug not nullable

Revision ID: 1eebb26c2d05
Revises: 5ef909b2e692
Create Date: 2022-02-21 15:31:12.660102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eebb26c2d05'
down_revision = '5ef909b2e692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projet', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('projet', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projet', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('projet', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
