"""projet section

Revision ID: 27f46bb3ff09
Revises: 5652c471d34b
Create Date: 2022-05-03 11:57:05.359689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f46bb3ff09'
down_revision = '5652c471d34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projet_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('projet', 'ou')
    op.drop_column('projet', 'pour_qui')
    op.drop_column('projet', 'pourquoi')
    op.drop_column('projet', 'quoi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('quoi', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projet', sa.Column('pourquoi', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projet', sa.Column('pour_qui', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projet', sa.Column('ou', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('projet_section')
    # ### end Alembic commands ###
