"""Keypoint in index content

Revision ID: 54542131acb3
Revises: c304382a2f5d
Create Date: 2022-08-19 21:57:15.041154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54542131acb3'
down_revision = 'c304382a2f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_content', sa.Column('keypoint1_icon', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint1_title', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint1_content', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint2_icon', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint2_title', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint2_content', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint3_icon', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint3_title', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint3_content', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint4_icon', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint4_title', sa.String(length=255), nullable=True))
    op.add_column('index_content', sa.Column('keypoint4_content', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_content', 'keypoint4_content')
    op.drop_column('index_content', 'keypoint4_title')
    op.drop_column('index_content', 'keypoint4_icon')
    op.drop_column('index_content', 'keypoint3_content')
    op.drop_column('index_content', 'keypoint3_title')
    op.drop_column('index_content', 'keypoint3_icon')
    op.drop_column('index_content', 'keypoint2_content')
    op.drop_column('index_content', 'keypoint2_title')
    op.drop_column('index_content', 'keypoint2_icon')
    op.drop_column('index_content', 'keypoint1_content')
    op.drop_column('index_content', 'keypoint1_title')
    op.drop_column('index_content', 'keypoint1_icon')
    # ### end Alembic commands ###
