"""Initial migration

Revision ID: 5652c471d34b
Revises: 
Create Date: 2022-04-12 17:19:19.212213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5652c471d34b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('promo', sa.Integer(), nullable=True),
    sa.Column('courte_description', sa.String(length=255), nullable=True),
    sa.Column('quoi', sa.Text(), nullable=True),
    sa.Column('ou', sa.Text(), nullable=True),
    sa.Column('pour_qui', sa.Text(), nullable=True),
    sa.Column('pourquoi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('projet')
    # ### end Alembic commands ###
