"""porjet cover_image delete

Revision ID: 76f2da65cae5
Revises: f21afb5321ac
Create Date: 2022-04-04 11:37:43.432257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f2da65cae5'
down_revision = 'f21afb5321ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projet', 'cover_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('cover_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
