"""table projet slug quoi

Revision ID: 7af701415774
Revises: 1eebb26c2d05
Create Date: 2022-02-21 15:39:18.609376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af701415774'
down_revision = '1eebb26c2d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('quoi', sa.Text(), nullable=True))
    op.drop_column('projet', 'qui')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('qui', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projet', 'quoi')
    # ### end Alembic commands ###
