"""Index content

Revision ID: c304382a2f5d
Revises: f71566ea9723
Create Date: 2022-08-19 20:48:31.246778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c304382a2f5d'
down_revision = 'f71566ea9723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bienvenue', sa.Text(), server_default='', nullable=True),
    sa.Column('don', sa.Text(), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_content')
    # ### end Alembic commands ###
