"""table projet sous_titre image

Revision ID: f21afb5321ac
Revises: 7af701415774
Create Date: 2022-02-21 16:03:35.564309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21afb5321ac'
down_revision = '7af701415774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('courte_description', sa.String(length=255), nullable=True))
    op.add_column('projet', sa.Column('cover_image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projet', 'cover_image')
    op.drop_column('projet', 'courte_description')
    # ### end Alembic commands ###
