"""Remove projet section

Revision ID: f71566ea9723
Revises: 60b63ea26609
Create Date: 2022-05-05 12:08:55.984280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71566ea9723'
down_revision = '60b63ea26609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projet_section')
    op.add_column('projet', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projet', 'content')
    op.create_table('projet_section',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('projet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], name='projet_section_projet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='projet_section_pkey')
    )
    # ### end Alembic commands ###
