"""projet section form

Revision ID: fbd38801c473
Revises: 60b63ea26609
Create Date: 2022-05-03 19:08:38.579259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd38801c473'
down_revision = '60b63ea26609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projet_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('projet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projet_id'], ['projet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projet', sa.Column('is_archive', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projet', sa.Column('is_visible', sa.Boolean(), server_default='true', nullable=False))
    op.drop_column('projet', 'ou')
    op.drop_column('projet', 'pour_qui')
    op.drop_column('projet', 'quoi')
    op.drop_column('projet', 'pourquoi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projet', sa.Column('pourquoi', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projet', sa.Column('quoi', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projet', sa.Column('pour_qui', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('projet', sa.Column('ou', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projet', 'is_visible')
    op.drop_column('projet', 'is_archive')
    op.drop_table('projet_section')
    # ### end Alembic commands ###
